# Generated by Django 4.1.3 on 2022-11-12 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proctorx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_purchased',
        ),
        migrations.RemoveField(
            model_name='session',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='session',
            name='exam_length',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], db_column='exam length (hrs)', default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='exam_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='session',
            name='exam_date',
            field=models.DateField(default=datetime.date(2022, 11, 12)),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField()),
                ('cost', models.FloatField()),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctorx.session')),
            ],
        ),
    ]
