# Generated by Django 4.1.3 on 2022-11-13 01:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proctorx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exam_length',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], db_column='exam length (hrs)', default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='exam_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='exam_date',
            field=models.DateField(default=datetime.date(2022, 11, 12)),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
