# Generated by Django 4.1.3 on 2022-11-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
