# Generated by Django 4.1.3 on 2022-11-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0002_remove_session_cost_remove_session_date_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
