# Generated by Django 4.1.3 on 2022-11-12 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exam_time2',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
