# Generated by Django 4.1.3 on 2022-12-11 21:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0003_remove_session_exam_date_remove_session_exam_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='exam_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 29, 29, 217915)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 29, 29, 217915))),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proctorx.order'),
        ),
    ]
