# Generated by Django 4.1.3 on 2022-11-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0004_session_exam_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exam_time2',
        ),
    ]
