# Generated by Django 4.1.7 on 2024-01-18 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0004_alter_session_exam_date_time_order_session_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 22, 15, 58, 533814)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 22, 15, 58, 533814)),
        ),
        migrations.AlterField(
            model_name='session',
            name='exam_date_time',
            field=models.DateField(),
        ),
    ]
