# Generated by Django 4.1.7 on 2024-01-18 03:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0005_alter_order_date_placed_alter_session_date_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 22, 25, 11, 382751)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='exam_date_time',
            field=models.DateTimeField(),
        ),
    ]
