# Generated by Django 4.1.3 on 2022-11-12 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0005_remove_session_exam_time2'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exam_time2',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='session',
            name='exam_time3',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
