# Generated by Django 4.1.3 on 2022-11-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0006_session_exam_time2_session_exam_time3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exam_time',
        ),
    ]
