# Generated by Django 4.1.3 on 2022-11-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0007_remove_session_exam_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='exam_time2',
            new_name='exam_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='exam_time3',
        ),
    ]
