# Generated by Django 4.1.3 on 2022-11-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0008_rename_exam_time2_session_exam_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
