# Generated by Django 4.1.3 on 2022-11-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorx', '0009_rename_payments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
